#!/usr/bin/env python3

#   list_worktypes
LIST_WORKTYPE_REMOVE = 'LIST_WORKTYPE_REMOVE'
LIST_WORKTYPE_EXISTS = 'LIST_WORKTYPE_EXISTS'


#   users
USER_ROOT = 'root'

#   time types
TIME_TYPE_SECONDS_EPOCH = 'TIME_TYPE_SECONDS_EPOCH'
TIME_TYPE_TODAY = 'TIME_TYPE_TODAY'
TIME_TYPE_TODAY_LONG = 'TIME_TYPE_TODAY_LONG'
TIME_TYPE_HOURS = 'TIME_TYPE_HOURS'

#   types
TYPE_FILE = 'TYPE_FILE'
TYPE_DIR = 'TYPE_DIR'
TYPE_HOST = 'TYPE_HOST'

#   action
ACTION_REMOVE = 'ACTION_REMOVE'
ACTION_CREATE = 'ACTION_CREATE'
ACTION_FIND = 'ACTION_FIND'
ACTION_EXISTS = 'ACTION_EXISTS'


#   values
VALUE_DEFAULT = 'DEFAULT'
VALUE_ERROR = 'ERROR'
VALUE_YES = 'yes'
VALUE_NO = 'no'
VALUE_PASSED = 'passed'


#   logging
LOG_ERROR = 'ERROR'
LOG_OTHER = 'OTHER'
LOG_IMPORTANT = 'IMPORTANT'

LOGNAME_MAIN = 'MAIN'
LOGNAME_DEBUG = 'DEBUG'
LOGNAME_INFO = 'INFO'
LOGNAME_ERROR = 'ERROR'
LOGNAME_IMPORTANT = 'IMPORTANT'

MODE_LOG_ERROR = 'LOG_MODE_ERROR'
MODE_LOG_NORMAL = 'LOG_MODE_NORMAL'
MODE_LOG_DEBUG = 'LOG_MODE_DEBUG'

#   other
NOT_FOUND = 'NOT_FOUND'


#   file extensions
EXT_LOG = '.log'
EXT_TGZ = '.tar.gz'


#   dirs
DIR_ROOT = '/root/'
DIR_SSH_ROOT = DIR_ROOT + '.ssh/'
DIR_TMP = DIR_ROOT + 'tmp/'
DIR_TESTING = DIR_ROOT + 'testing/'
DIR_SSH_CONFIGS = '/etc/ssh/'


#   files
FILE_ID_RSA = 'id_rsa'
FILE_ID_RSA_PUB = 'id_rsa.pub'
FILE_SSH_CONFIG = 'ssh_config'
FILE_SSHD_CONFIG = 'sshd_config'


#   flags
FLAG_TESTING = 'FLAG_TESTING'


#   other
THREADED = True
NOT_THREADED = False

#   types
TYPE_LIST = 'TYPE_LIST'
TYPE_DICT = 'TYPE_DICT'
TYPE_STRING = 'TYPE_STRING'
TYPE_INTEGER = 'TYPE_INTEGER'
TYPE_FLOAT = 'TYPE_FLOAT'


